paths:
  data_url: "https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"
  config_path: "./config/config.yaml"
  data_path: "./data/input.txt"
  model_path: "./model/"
  model_base_name: "bigram_language_model"
  model_extension: "pth"
  itos_path: "./data/itos.json"

hyperparameters:
  batch_size: 64
  block_size: 256
  max_iters: 5000
  eval_interval: 500
  learning_rate: 3e-4
  eval_iters: 200
  train_val_split: 0.9
  attention_heads: 6
  n_layers: 6
  dropout: 0.2

vocabulary:
  n_embd: 384

generation:
  max_new_tokens: 1000
  model_version: 2